#!/bin/bash

touch /tmp/.dmenu_history &\
cache=/tmp/dmenu_cache
freq=/tmp/.dmenu_history
aliases=~/.profile
source $aliases

(compgen -a; compgen -c | grep -vxF "$(compgen -a)") | sort | tail -n +10 > $cache

sorted=$(sort $freq | uniq -c | sort -hr | colrm 1 8)
cmd=`(echo "$sorted"; cat $cache | grep -vxF "$sorted") | dmenu "$@"`
if ! [ "$cmd" == "" ] && ! [ "$(grep `echo $cmd | tr -d ':;'` $cache)" == "" ]; then
    echo $cmd | tr -d ':;' >> $freq

    cmdexec=$(alias | grep "`echo $cmd | tr -d ':;'`=" | cut -f2 -d"'" | tr -d "'")
    if [ -z "$cmdexec" ]; then
        cmdexec=`echo $cmd | tr -d ':;'`
    fi

    if [[ $cmd == *';'* ]]; then
        cmdexec="st -e $cmdexec"
    fi
    if [[ $cmd == *':'* ]]; then
        cmdexec="xdotool mousemove - 1 mousemove restore; gksu '$cmdexec'"
    fi

    echo "$cmdexec" | bash
fi
